# Generated by Django 4.1.7 on 2023-04-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_experience_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='skills',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='experience',
            name='about',
            field=models.CharField(max_length=350),
        ),
    ]
